### ISSUE TITLE
代码运行报错

### ISSUE THREAD

**Issue by Tutu0521** [YimianDai/open-alcnet#8]
1. 在运行visualize_local_contrast_networks.py时报错：
Traceback (most recent call last):
File "visualize_local_contrast_networks.py", line 254, in
trainer.validation(0)
File "visualize_local_contrast_networks.py", line 227, in validation
pred = self.net(exp_img)
File "/mistgpu/site-packages/mxnet/gluon/block.py", line 682, in call
out = self.forward(*args)
File "/mistgpu/site-packages/mxnet/gluon/block.py", line 1309, in forward
return self.hybrid_forward(ndarray, x, *args, **params)
File "/home/mist/open-alcnet-master/model/contrast.py", line 518, in hybrid_forward
x = self.stem(x) # sub 2
File "/mistgpu/site-packages/mxnet/gluon/block.py", line 682, in call
out = self.forward(*args)
File "/mistgpu/site-packages/mxnet/gluon/block.py", line 1309, in forward
return self.hybrid_forward(ndarray, x, *args, **params)
File "/mistgpu/site-packages/mxnet/gluon/nn/basic_layers.py", line 119, in hybrid_forward
x = block(x)
File "/mistgpu/site-packages/mxnet/gluon/block.py", line 682, in call
out = self.forward(*args)
File "/mistgpu/site-packages/mxnet/gluon/block.py", line 1302, in forward
params = {k: v.data(ctx) for k, v in self._reg_params.items()}
File "/mistgpu/site-packages/mxnet/gluon/block.py", line 1302, in
params = {k: v.data(ctx) for k, v in self._reg_params.items()}
File "/mistgpu/site-packages/mxnet/gluon/parameter.py", line 574, in data
return self._check_and_get(self._data, ctx)
File "/mistgpu/site-packages/mxnet/gluon/parameter.py", line 228, in _check_and_get
self.name, str(ctx), str(self._ctx_list)))
RuntimeError: Parameter 'mpcmresnetfpn0_batchnorm0_gamma' was not initialized on context cpu(0). It was only initialized on [gpu(0)].

2. 在运行train_alcnet.py时报错：
Traceback (most recent call last):
  File "/omnisky4/l/open-alcnet-master/train_alcnet.py", line 359, in <module>
    trainer = Trainer(args)
  File "/omnisky4/l/open-alcnet-master/train_alcnet.py", line 221, in __init__
    model.initialize(init=init.MSRAPrelu(), ctx=args.ctx, force_reinit=True)
UnboundLocalError: local variable 'model' referenced before assignment

**Comment by nestor0003** [comment]
val时出了同样的RuntimeError: mpcmresnetfpn0_batchnorm0_gamma...，环境是mxnet-cu100==1.7.0,gluoncv=0.10.4.post4,python==3.8.0

**Comment by nestor0003** [comment]
希望戴博士在install 部分能否给出具体的环境配置版本，十分感谢！

**Comment by CPF-314127** [comment]
请问您解决了吗

**Comment by nestor0003** [comment]
没
